// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: autohaus.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdresse = `-- name: CreateAdresse :exec
INSERT INTO adresse (plz, ort, land, autohaus_id)
VALUES ($1, $2, $3, $4)
`

type CreateAdresseParams struct {
	Plz        string `db:"plz" json:"plz"`
	Ort        string `db:"ort" json:"ort"`
	Land       string `db:"land" json:"land"`
	AutohausID int32  `db:"autohaus_id" json:"autohaus_id"`
}

func (q *Queries) CreateAdresse(ctx context.Context, arg CreateAdresseParams) error {
	_, err := q.db.Exec(ctx, createAdresse,
		arg.Plz,
		arg.Ort,
		arg.Land,
		arg.AutohausID,
	)
	return err
}

const createAuto = `-- name: CreateAuto :exec
INSERT INTO auto (kennzeichen, marke, modell, baujahr, autohaus_id)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAutoParams struct {
	Kennzeichen string `db:"kennzeichen" json:"kennzeichen"`
	Marke       string `db:"marke" json:"marke"`
	Modell      string `db:"modell" json:"modell"`
	Baujahr     int32  `db:"baujahr" json:"baujahr"`
	AutohausID  int32  `db:"autohaus_id" json:"autohaus_id"`
}

func (q *Queries) CreateAuto(ctx context.Context, arg CreateAutoParams) error {
	_, err := q.db.Exec(ctx, createAuto,
		arg.Kennzeichen,
		arg.Marke,
		arg.Modell,
		arg.Baujahr,
		arg.AutohausID,
	)
	return err
}

const createAutohaus = `-- name: CreateAutohaus :one
INSERT INTO autohaus (version, name, username, email, anzahl_fahrzeuge, gruendungsdatum, homepage, telefonnummer, erzeugt, aktualisiert)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id
`

type CreateAutohausParams struct {
	Version         int32       `db:"version" json:"version"`
	Name            string      `db:"name" json:"name"`
	Username        string      `db:"username" json:"username"`
	Email           string      `db:"email" json:"email"`
	AnzahlFahrzeuge int32       `db:"anzahl_fahrzeuge" json:"anzahl_fahrzeuge"`
	Gruendungsdatum pgtype.Date `db:"gruendungsdatum" json:"gruendungsdatum"`
	Homepage        pgtype.Text `db:"homepage" json:"homepage"`
	Telefonnummer   pgtype.Text `db:"telefonnummer" json:"telefonnummer"`
}

func (q *Queries) CreateAutohaus(ctx context.Context, arg CreateAutohausParams) (int32, error) {
	row := q.db.QueryRow(ctx, createAutohaus,
		arg.Version,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.AnzahlFahrzeuge,
		arg.Gruendungsdatum,
		arg.Homepage,
		arg.Telefonnummer,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getAdresseByAutohausId = `-- name: GetAdresseByAutohausId :one
SELECT id, plz, ort, land, autohaus_id
FROM adresse
WHERE autohaus_id = $1
`

func (q *Queries) GetAdresseByAutohausId(ctx context.Context, autohausID int32) (Adresse, error) {
	row := q.db.QueryRow(ctx, getAdresseByAutohausId, autohausID)
	var i Adresse
	err := row.Scan(
		&i.ID,
		&i.Plz,
		&i.Ort,
		&i.Land,
		&i.AutohausID,
	)
	return i, err
}

const getAutohausById = `-- name: GetAutohausById :one
SELECT id, version, name, username, email, anzahl_fahrzeuge, gruendungsdatum, homepage, telefonnummer, erzeugt, aktualisiert
FROM autohaus
WHERE id = $1
`

func (q *Queries) GetAutohausById(ctx context.Context, id int32) (Autohau, error) {
	row := q.db.QueryRow(ctx, getAutohausById, id)
	var i Autohau
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.AnzahlFahrzeuge,
		&i.Gruendungsdatum,
		&i.Homepage,
		&i.Telefonnummer,
		&i.Erzeugt,
		&i.Aktualisiert,
	)
	return i, err
}

const getAutosByAutohausId = `-- name: GetAutosByAutohausId :many
SELECT id, kennzeichen, marke, modell, baujahr, autohaus_id
FROM auto
WHERE autohaus_id = $1
`

func (q *Queries) GetAutosByAutohausId(ctx context.Context, autohausID int32) ([]Auto, error) {
	rows, err := q.db.Query(ctx, getAutosByAutohausId, autohausID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auto
	for rows.Next() {
		var i Auto
		if err := rows.Scan(
			&i.ID,
			&i.Kennzeichen,
			&i.Marke,
			&i.Modell,
			&i.Baujahr,
			&i.AutohausID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
