// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Adresse struct {
	ID         int32  `db:"id" json:"id"`
	Plz        string `db:"plz" json:"plz"`
	Ort        string `db:"ort" json:"ort"`
	Land       string `db:"land" json:"land"`
	AutohausID int32  `db:"autohaus_id" json:"autohaus_id"`
}

type Auto struct {
	ID          int32  `db:"id" json:"id"`
	Kennzeichen string `db:"kennzeichen" json:"kennzeichen"`
	Marke       string `db:"marke" json:"marke"`
	Modell      string `db:"modell" json:"modell"`
	Baujahr     int32  `db:"baujahr" json:"baujahr"`
	AutohausID  int32  `db:"autohaus_id" json:"autohaus_id"`
}

type Autohau struct {
	ID              int32            `db:"id" json:"id"`
	Version         int32            `db:"version" json:"version"`
	Name            string           `db:"name" json:"name"`
	Username        string           `db:"username" json:"username"`
	Email           string           `db:"email" json:"email"`
	AnzahlFahrzeuge int32            `db:"anzahl_fahrzeuge" json:"anzahl_fahrzeuge"`
	Gruendungsdatum pgtype.Date      `db:"gruendungsdatum" json:"gruendungsdatum"`
	Homepage        pgtype.Text      `db:"homepage" json:"homepage"`
	Telefonnummer   pgtype.Text      `db:"telefonnummer" json:"telefonnummer"`
	Erzeugt         pgtype.Timestamp `db:"erzeugt" json:"erzeugt"`
	Aktualisiert    pgtype.Timestamp `db:"aktualisiert" json:"aktualisiert"`
}
